eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8060

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: APP-SERVICE
#          uri: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8070/home
          uri: lb://APP-SERVICE
          predicates:
            - Path=/home
#            - Path=/APP-SERVICE/**
          stripPrefix: false
