eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8060

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: app-service
<<<<<<< HEAD
#          uri: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8070/home
          predicates:
            - Path=/home
          stripPrefix: false
=======
          predicates:
            - Path=/home
>>>>>>> faa7af62e67a7d8cfbf381e9e156522be3537dd8
