eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8060

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: app-service
#          uri: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8070/home
          uri: lb://app-service
          predicates:
            - Path=/home